variables:
  DEPLOYMENT_IMAGE: mattanddev/sta-bot:latest

stages:
  - deploy


deploy-to-k8s:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl apply -f k8s
