apiVersion: apps/v1
kind: Deployment
metadata:
  name: sta-bot
spec:
  selector:
    matchLabels:
      app: sta-bot
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sta-bot
    spec:
      containers:
      - name: sta-bot
        image: mattanddev/sta-bot:latest
        ports:
        - containerPort: 3100