apiVersion: v1
kind: Service
metadata:
  name: sta-bot
spec:
  ports:
  - port: 80
    targetPort: 3100
  selector:
    app: sta-bot
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 80
  selector:
    app: sta-bot
